import { PostgresUserStore } from '../auth/postgres-user-store';
import { pool } from '../db/client';

// Mock the pg pool so we can verify the SQL without a real database
jest.mock('../db/client', () => ({
  pool: {
    query: jest.fn(),
  },
}));

const mockQuery = pool.query as jest.MockedFunction<typeof pool.query>;

describe('PostgresUserStore', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('create()', () => {
    test('generates a UUID for the id column (fixes 500 error)', async () => {
      mockQuery.mockResolvedValue({
        rows: [
          {
            id: '550e8400-e29b-41d4-a716-446655440000',
            username: 'newuser',
            name: 'New User',
            role: 'VIEWER',
            password_hash: 'salt:hash',
          },
        ],
        rowCount: 1,
      } as never);

      const store = new PostgresUserStore();
      const user = await store.create('newuser', 'New User', 'password123', 'viewer');

      // Verify the INSERT includes the id column
      const [sql, params] = mockQuery.mock.calls[0] as unknown as [string, unknown[]];
      expect(sql).toContain('INSERT INTO "User"');
      expect(sql).toContain('(id, username, name, role, "passwordHash")'); // id column now included
      expect(sql).not.toMatch(/VALUES \(\$1, \$2, \$3, \$4\)/); // old query without id
      expect(sql).toMatch(/VALUES \(\$1, \$2, \$3, \$4, \$5\)/); // new query with id

      // Verify the first parameter is a UUID (generated by randomUUID)
      expect(params[0]).toEqual(expect.any(String));
      expect(params[0]).toMatch(
        /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/,
      );

      // Verify the returned user has the correct fields
      expect(user).toMatchObject({
        id: '550e8400-e29b-41d4-a716-446655440000',
        username: 'newuser',
        name: 'New User',
        role: 'viewer',
      });
      expect(user).not.toHaveProperty('passwordHash');
    });

    test('uppercases the role for the database enum', async () => {
      mockQuery.mockResolvedValue({
        rows: [
          {
            id: '550e8400-e29b-41d4-a716-446655440001',
            username: 'admin2',
            name: 'Admin Two',
            role: 'ADMIN',
            password_hash: 'salt:hash',
          },
        ],
        rowCount: 1,
      } as never);

      const store = new PostgresUserStore();
      await store.create('admin2', 'Admin Two', 'password123', 'admin');

      const [, params] = mockQuery.mock.calls[0] as unknown as [string, unknown[]];
      // role is the 4th parameter (index 3) after id, username, name
      expect(params[3]).toBe('ADMIN');
    });

    test('hashes the password before storing', async () => {
      mockQuery.mockResolvedValue({
        rows: [
          {
            id: '550e8400-e29b-41d4-a716-446655440002',
            username: 'hashuser',
            name: 'Hash User',
            role: 'VIEWER',
            password_hash: 'salt:hash',
          },
        ],
        rowCount: 1,
      } as never);

      const store = new PostgresUserStore();
      await store.create('hashuser', 'Hash User', 'password123', 'viewer');

      const [, params] = mockQuery.mock.calls[0] as unknown as [string, unknown[]];
      // passwordHash is the 5th parameter (index 4)
      const storedHash = params[4] as string;
      expect(storedHash).toContain(':');
      expect(storedHash.split(':')).toHaveLength(2);
    });
  });
});
